config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  # resources :sites
  get 'measurements/:site_id/' => 'measurements#show'
  get 'react/' => 'static_pages#root'
  namespace :api, defaults: { format: :json } do
    get 'sites' => 'sites#api_index'
    post 'series' => 'sites#load_series_data'
    get 'search' => 'sites#search'
    get 'series_csv/:id/' => 'sites#series_csv'
    get 'saved_selections' => 'saved_selections#ajax_get_all'
    post 'save_selections' => 'saved_selections#ajax_create'
    post 'csv_download' => 'sites#csv_download'

  end
  root 'static_pages#root'
  get 'd3test' => 'static_pages#advanced_d3_test'

  get 'data.tsv' => 'static_pages#data'
end

app/models/measurement.rb
# frozen_string_literal: true

# A single data point
class Measurement < ActiveRecord::Base
  MEASUMENT_NAME = 'Groundwater Level'
  belongs_to :site

  def self.as_csv
    CSV.generate(col_sep: ',', row_sep: "\r\n") do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/saved_selection.rb
# frozen_string_literal: true

# Set of site ids saved by user
class SavedSelection < ActiveRecord::Base
  belongs_to :user
  validates :name, :uniqueness => { :scope => :user_id }
end

app/models/site.rb
# frozen_string_literal: true

class Site < ActiveRecord::Base
  has_many :measurements

  reverse_geocoded_by :latitude, :longitude do |obj, results|
    if geo == results.first
      obj.address = geo.address.split(',')[0]
      obj.city = geo.city
      obj.zip = geo.postal_code
      obj.state = geo.state_code
    end
  end

  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

  def self.geocode_all
    @sites = Site.all
    count = 0
    @sites.each do |site|
      next if site.address
      site.update(id: site.id)
      count += 1
      sleep(2) if (count % 3).zero?
    end
    p "#{count} sites have been successfully geocoded."
  end

  after_validation :reverse_geocode # auto-fetch address
end

app/models/user.rb
# frozen_string_literal: true

# User login model
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :saved_selections
end

app/controllers/api/saved_selections_controller.rb
# frozen_string_literal: true

# SavedSelectionsController
class Api::SavedSelectionsController < ApplicationController
  before_action :authenticate_user!
  # Get all saved selections for logged in user.
  def ajax_get_all
    hash = {}
    current_user.saved_selections.each do |s|
      hash[s.name] = s.site_ids
    end
    render :json => hash
  end

  # Create a new saved selection
  def ajax_create
    created = []
    params[:selections]&.keys&.each do |name|
      created << current_user.saved_selections.create!(
        :name     => name,
        :site_ids => params[:selections][name].map(&:to_i)
      )
    end

    render :json => { :success => true, :created => created, :authToken => form_authenticity_token }
  end

  # Delete a saved selection
  def ajax_delete
    selection = current_user.saved_selections.where(:name => params[:name])
    selection.destroy
    render :json => { :success => true, :authToken => form_authenticity_token }
  end
end

app/controllers/api/sites_controller.rb
# frozen_string_literal: true

class Api::SitesController < ApplicationController
  before_action :set_site, only: :series_csv

  def api_index
    sites = Site.joins(:measurements).select('sites.*, count(measurements.id) measure_count').group(:id)
    data_block = sites.map do |site|
      {
        id: site.id,
        site_name: site.site_name,
        lng: site.longitude,
        lat: site.latitude,
        address: site.address,
        city: site.city,
        state: site.state,
        zip: site.zip,
        measure_count: site.measure_count
      }
    end
    
    render json: data_block
  end

  def load_series_data
    get_measurments
    data_block = {}
    @measurements.each do |measurement|
      data_block[measurement.site_id] ||= []
      data_block[measurement.site_id] << {
        measureDate: measurement.measure_date.to_time.utc.to_i * 1000,
        siteId:      measurement.site_id,
        level:       measurement.level.to_f
      }
    end
    render json: data_block
  end

  def csv_download
    get_measurments
    attributes = %w{id site_id site_name measure_date level units measure_type data_provider }
    csv = CSV.generate(headers: true) do |csv|
      csv << attributes

      @measurements.each do |measurement|
        csv << attributes.map{ |attr| measurement.send(attr) }
      end
    end
    respond_to do |format|
      format.json { send_data csv, filename: "users-#{Date.today}.csv" }
    end
  end

  def series_csv
    render text: @site.measurements.pluck(:level).join(',')
  end

  private

  def get_measurments
    @measurements = Measurement.where(site_id: params[:pullIds]).order(:measure_date)
    if params[:filterDates]
      filter_dates = params[:filterDates].split(',')
      @start_date = filter_dates.first
      @end_date = filter_dates.last
      @measurements = @measurements.where("measure_date BETWEEN ? and ?", @start_date, @end_date)
    end

  end

  def set_site
    @site = Site.find(params[:id])
  end

  def site_params
    params.require(:site).permit(:city, :state, :zip, :measure_count)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

# app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    success = false
    user = User.find_for_authentication(email: params[:user][:email])
    success = true if user&.valid_password?(params[:user][:password])
    success = true if user.nil? && valid_email(params[:user][:email])
    if success
      sign_in(user)
      render json: { success: true, loggedIn: true, authToken: form_authenticity_token }
    else
      render json: { success: false, loggedIn: true, authToken: form_authenticity_token, errors: ['Login failed.'] }
    end
  end

  def update
    super
  end

  private

  def valid_email(email)
    /^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$/.match(email)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    user = User.find_for_authentication(email: params[:user][:email])

    if user&.valid_password?(params[:user][:password])
      sign_in(user)
      render json: { success: true, loggedIn: true, authToken: form_authenticity_token }
    else
      render json: { success: false, loggedIn: true, authToken: form_authenticity_token, errors: ['Login failed.'] }
    end
  end

  def destroy
    sign_out if current_user

    render json: { success: true, loggedIn: false, authToken: form_authenticity_token }
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def json_handoff(key, value)
    <<-TEXT.html_safe
    <script>
      (function() {
        if (typeof(DP) === 'undefined') {
          DP = {};
        }
        var #{key} = #{ActiveSupport::JSON.encode(value)};
        DP.#{key} = #{key};
      })();
    </script>
    TEXT
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/sites_helper.rb
# frozen_string_literal: true

module SitesHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spatiotemporal Data Exploration Tool (SDET)</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

  <%= csrf_meta_tags %>
</head>
<p id="notice"><%= notice %></p>
<body>

<%= yield %>
<script
  src="<%= "https://maps.googleapis.com/maps/api/js?key=#{ENV['google_maps_api_key']}&libraries=drawing&callback=loadMap" %>"
  async
  defer>
</script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_name %><br>
    <%= f.text_field :site_name %>
  </div>
  <div class="field">
    <%= f.label :well_reference %><br>
    <%= f.text_field :well_reference %>
  </div>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
    <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
      <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
      <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
      <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>





<h1>Listing Sites</h1>
<% if true%>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div id="map_canvas" style="height: 800px; width:1200px;"></div>
  </tbody>
</table>
<% end %>
<br>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map_canvas'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);

  handler.fitMapToBounds();

});
</script>
<script src="http://d3js.org/d3.v3.min.js"></script>

app/views/sites/indexsimple.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<style> /* set the CSS */

body { font: 12px Arial;}

path { 
    stroke: steelblue;
    stroke-width: 2;
    fill: none;
}

.axis path,
.axis line {
    fill: none;
    stroke: grey;
    stroke-width: 1;
    shape-rendering: crispEdges;
}

</style>
<body>

<!-- load the d3.js library -->    
<script src="http://d3js.org/d3.v3.min.js"></script>

<script>

// Set the dimensions of the canvas / graph
var margin = {top: 30, right: 20, bottom: 30, left: 50},
    width = 600 - margin.left - margin.right,
    height = 270 - margin.top - margin.bottom;

// Parse the date / time
var parseDate = d3.time.format("%Y-%m-%d").parse;

// Set the ranges
var x = d3.time.scale().range([0, width]);
var y = d3.scale.linear().range([height, 0]);

// Define the axes
var xAxis = d3.svg.axis().scale(x)
    .orient("bottom").ticks(5);

var yAxis = d3.svg.axis().scale(y)
    .orient("left").ticks(5);

// Define the line
var valueline = d3.svg.line()
    .x(function(d) { return x(d.measure_date); })
    .y(function(d) { return y(d.level); });
    
// Adds the svg canvas
var svg = d3.select("body")
    .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
    .append("g")
        .attr("transform", 
              "translate(" + margin.left + "," + margin.top + ")");

// Get the data
d3.csv('/measurements/2.csv', function(error, data) {
    data.forEach(function(d) {
        d.measure_date = parseDate(d.measure_date);
        d.level = +d.level;
    });

    // Scale the range of the data
    x.domain(d3.extent(data, function(d) { return d.measure_date; }));
    y.domain([0, d3.max(data, function(d) { return d.level; })]);

    // Add the valueline path.
    svg.append("path")
        .attr("class", "line")
        .attr("d", valueline(data));

    // Add the X Axis
    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    // Add the Y Axis
    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis);

});

</script>
</body>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>





<h1>Displaying <%= Measurement::MEASUMENT_NAME %> data</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div id="map_canvas" style="height: 300px; width:1200px;"></div>
  </tbody>
</table>


<br>


<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map_canvas'}}, function(){
 markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();

});
</script>


<script>

// Set the dimensions of the canvas / graph
var margin = {top: 30, right: 20, bottom: 30, left: 50},
    width = 1200 - margin.left - margin.right,
    height = 600 - margin.top - margin.bottom;

// Parse the date / time
var parseDate = d3.time.format("%Y-%m-%d").parse;

// Set the ranges
var x = d3.time.scale().range([0, width]);
var y = d3.scale.linear().range([height, 0]);

// Define the axes
var xAxis = d3.svg.axis().scale(x)
    .orient("bottom").ticks(5);

var yAxis = d3.svg.axis().scale(y)
    .orient("left").ticks(5);

// Define the line
var valueline = d3.svg.line()
    .x(function(d) { return x(d.measure_date); })
    .y(function(d) { return y(d.level); });

// Adds the svg canvas
var svg = d3.select("body")
    .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
    .append("g")
        .attr("transform",
              "translate(" + margin.left + "," + margin.top + ")");

// Get the data
d3.csv('/measurements/<%= params[:id]%>.csv', function(error, data) {
    data.forEach(function(d) {
        d.measure_date = parseDate(d.measure_date);
        d.level = +d.level;
    });

    // Scale the range of the data
    x.domain(d3.extent(data, function(d) { return d.measure_date; }));
    //x.domain([parseDate("1900-01-01"),parseDate("2016-01-01"])
    y.domain([0, d3.max(data, function(d) { return d.level; })]);

    // Add the valueline path.
    svg.append("path")
        .attr("class", "line")
        .attr("d", valueline(data));

    // Add the X Axis
    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    // Add the Y Axis
    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis);

});

</script>

<%= link_to 'New Site', new_site_path %>

app/views/sites/showmulti.html.erb
<html>
	<head>
		<title>Interactive Line Graph</title>
		<script src="http://d3js.org/d3.v2.js"></script>
		<!-- 
			using JQuery for element dimensions
			This is a small aspect of this example so it can be removed fairly easily if needed.
		-->
		<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>

		<style>
			body {
				font-family: "Helvetica Neue", Helvetica;
			}
					
			p {
				clear:both;
				top: 20px;
			}		
					
			div.aGraph {
				margin-bottom: 30px;
			}
		</style>
	</head>
	<body>
		<div id="graph1" class="aGraph" style="position:relative;width:100%;height:400px"></div>
	
	<div id="graph2" class="aGraph" style="float:left;position:relative;width:49%;height:200px"></div>
	<div id="graph3" class="aGraph" style="float:left;position:relative;width:49%;height:200px"></div>
	

	<script>
		/* 
		 * If running inside bl.ocks.org we want to resize the iframe to fit both graphs
		 */
		 if(parent.document.getElementsByTagName("iframe")[0]) {
			 parent.document.getElementsByTagName("iframe")[0].setAttribute('style', 'height: 650px !important');
		 }
	
		 /*
		 * Note how the 'data' object is added to here before rendering to provide decoration information.
		 * <p>
		 * This is purposefully done here instead of in data.js as an example of how data would come from a server
		 * and then have presentation information injected into it (rather than as separate arguments in another object)
		 * and passed into LineGraph.
		 *
		 * Also, CSS can be used to style colors etc, but this is also doable via the 'data' object so that the styling
		 * of different data points can be done in code which is often more natural for display names, legends, line colors etc
		 */
		 // add presentation logic for 'data' object using optional data arguments
		
		 data["displayNames"] = ["2xx","3xx","4xx","5xx"];
		 data["colors"] = ["green","orange","red","darkred"];
		 data["scale"] = "pow";
		 
		 // add presentation logic for 'data' object using optional data arguments
		 
		 data2["displayNames"] = ["2xx","3xx","4xx","5xx"];
		 data2["colors"] = ["green","orange","red","darkred"];
		 data2["scale"] = "linear";
		 
		 // add presentation logic for 'data' object using optional data arguments
		
		 data3["displayNames"] = ["Data1", "Data2"];
		 data3["axis"] = ["left", "right"];
		 data3["colors"] = ["#2863bc","#c8801c"];
		 data3["rounding"] = [2, 0];

		 // create graph now that we've added presentation config
		var l1 = new LineGraph({containerId: 'graph1', data: data});
		var l2 = new LineGraph({containerId: 'graph2', data: data2});
		var l3 = new LineGraph({containerId: 'graph3', data: data3});
		
	setInterval(function() {
		/*
		* The following will simulate live updating of the data (see dataA, dataB, dataC etc in data.js which are real examples)
		* This is being simulated so this example functions standalone without a backend server which generates data such as data.js contains.
		*/
		// for each data series ...
		var newData = [];
		data.values.forEach(function(dataSeries, index) {
			// take the first value and move it to the end
			// and capture the value we're moving so we can send it to the graph as an update
			var v = dataSeries.shift();
			dataSeries.push(v);
			// put this value in newData as an array with 1 value
			newData[index] = [v];
		})
		
		// we will reuse dataA each time
		dataA.values = newData;
		// increment time 1 step
		dataA.start = dataA.start + dataA.step;
		dataA.end = dataA.end + dataA.step; 
					
		l1.slideData(dataA);
	}, 2000);

		
	</script>



	</body>
</html>

app/views/static_pages/root.html.erb
<%= json_handoff 'dataPortal', {
  :loggedInEmail => current_user&.email,
  :measurementName => Measurement::MEASUMENT_NAME
  } %>
<div id="root">Please enable Javascript.</div>